language: node_js
node_js:
  - "10"
  - "12"

sudo: false
dist: trusty

cache:
  yarn: true

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn install --no-lockfile

script:
  - npm run test

after_success:
  - cat ./coverage/lcov.info | npm run coveralls
